function [Etot,output_shape,X,nBits] = sensing_consumption(ps,pg)
% ----------------------------------------------------------------------
%  Function which calculates the energy consumed for sensing audio data. 
%  Author: Fernando Rosas, KU Leuven
% ----------------------------------------------------------------------
% Syntaxis: sensing_consumption(ps,pg)
% Inputs:
% (1) ps,pg     struct containing all params of sensing and general resp.
% Outputs:
% (1) Etot      total energy consumed by the sensor [mJ]
% (2) X         vector which contains the percentage of the total consumption of
%               the sensor which correspond to X(1): ADC, X(2): LNA and X(3): mic.
% (3) NBits     number of bits generated by the sensor by recording following
%               the parameters duration, fs_audio and Nadc_mic.

% init default param
v2struct(ps); % expand field to workspace
v2struct(pg); % expand field to workspace

% General things
k = 1.3806488 * 10^-23;                                         % Boltzmann constant [m^2 kg / s^2 K]
T_K = T_C+273;                                                  % [K]
q = 1.60217657 * 10^-19;                                        % electron change [Q]
W_audio = fs_audio/2;                                           % audio bandwidth
u_T = k*T_K/q;                                                  % Thermal voltage

% energy consumption of the microphone
Emic = T*Pmic*channels;                                         % [mJ] = [s]*[mW] - eq. 5

% LNA consumption
I_LNA_mic = pi * u_T * 4*k*T_K*W_audio/2 * (NEF/v_n_in_rms)^2;  % [A] - eq. 7
Plna_sensor = Vdd_LNA_mic * I_LNA_mic * 10^3;                   % [mW] 
Elna_sensor = Plna_sensor * T * channels;                       % [mJ]

% ADC consumption
Padc = 2^Nadc_mic * fs_audio * FOMadc;                          % [mW] - eq. 10
Eadc = T*Padc*channels;                                         % [mJ] = [s]*[mW] - eq. 9

% Total energy consumption per data stream
Etot = Emic + Eadc + Elna_sensor;                               % [mJ]
output_shape([chid featid frameid]) = [channels 1 T*fs_audio];
nBits = T * fs_audio*Nadc_mic;
X = [Eadc,Elna_sensor,Emic]/Etot;
end



